# Generated by Django 4.1.2 on 2022-11-24 05:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_response_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='response',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='voice_record',
            field=models.FileField(default=django.utils.timezone.now, upload_to='records'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
