# Generated by Django 4.1.2 on 2022-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_question_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(default=100),
        ),
    ]
